version: 2

# build job parameters as a template
defaults: &defaults
  working_directory: ~/app
  docker:
    # the Docker image with Cypress dependencies
    - image: cypress/base:8
      environment:
        ## this enables colors in the output
        TERM: xterm

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - run: pwd
      - run: ls
      - restore_cache:
          keys:
            - v2-deps-{{ .Branch }}-{{ checksum "package-lock.json" }}
            - v2-deps-{{ .Branch }}-
            - v2-deps-
      - run: npm ci
      - save_cache:
          key: v2-deps-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - ~/.npm
            - ~/.cache
      - persist_to_workspace:
          root: ~/
          paths:
            - .cache
            - app

  testA:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/
      - run: ls -la cypress
      - run: ls -la cypress/integration
      - run:
          name: Running E2E tests A
          command: $(npm bin)/cypress run --spec cypress/integration/todo-actions-A.spec.js --reporter junit --reporter-options "mochaFile=results/my-test-output.xml"
      - store_test_results:
          path: results
      - store_artifacts:
          path: cypress/videos
      - store_artifacts:
          path: cypress/screenshots


  testB:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Running E2E tests B
          command: $(npm bin)/cypress run --spec cypress/integration/todo-actions-B.spec.js --reporter junit --reporter-options "mochaFile=results/my-test-output.xml"
      - store_test_results:
          path: results
      - store_artifacts:
          path: cypress/videos
      - store_artifacts:
          path: cypress/screenshots


  testC:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Running E2E tests C
          command: $(npm bin)/cypress run --spec cypress/integration/todo-actions-C.spec.js --reporter junit --reporter-options "mochaFile=results/my-test-output.xml"
      - store_test_results:
          path: results
      - store_artifacts:
          path: cypress/videos
      - store_artifacts:
          path: cypress/screenshots

  4x-electron:
    # use Cypress built Docker image with Node 10 and npm 6
    docker:
      - image: cypress/base:10
    # tells CircleCI to execute this job on 4 machines simultaneously
    parallelism: 4
    steps:
      - checkout
      # note: omitting caching for brevity
      # quickly install NPM dependencies
      - npm ci
      # load balance all tests across 4 CI machines
      - $(npm bin)/cypress run --parallel


workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - testA:
          requires:
            - build
      - testB:
          requires:
            - build
      - testC:
          requires:
            - build
      - 4x-electron:
          requires:
            - biuld